/*

 TILES_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 16
   Tile set      : D:\Projectes GameBoy\Pekoland\Tiles\tilesLevel.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TILES_MAPWidth 30
#define TILES_MAPHeight 16
#define TILES_MAPBank 0

extern unsigned char TILES_MAP[];

/* End of TILES_MAP.H */
